# LAB Product Validation Workflow - Enhanced Domain Model Configuration
# Compatible with Mendix 10.18.1 and Workflow Commons 3.12.1
project:
  name: "LABProductValidationWorkflow"
  description: "Complete LAB Product Validation Workflow System"
  version: "1.0.0"
  mendix_version: "10.18.1"
  workflow_commons_version: "3.12.1"

workflow:
  context_entity: "ProductValidation"
  name: "LAB_ProductValidation"
  description: "Main validation workflow with TRUE/FALSE outcomes for Mendix 10.18.1"

# Enhanced Entity Definitions with Comprehensive Comments and Documentation
entities:
  - name: "ProductValidation"
    description: "Main workflow context entity for product validation processes - inherits from System.WorkflowContext for Workflow Commons 3.12.1 integration"
    generalization: "System.WorkflowContext"
    purpose: "Central entity that tracks the entire validation workflow from start to completion"
    usage: "Created when a new validation workflow is initiated, updated throughout the process"
    security_notes: "Admin and Technician roles can create/modify, Viewer role has read-only access"
    attributes:
      - name: "ProductID"
        type: "String"
        length: 50
        description: "Unique identifier for the product being validated - critical for traceability"
        required: "Yes"
        validation: "Must be unique and not empty"
        usage_notes: "Used to link validation results back to the source product"
      - name: "WorkflowOutcome"
        type: "Boolean"
        description: "Final TRUE/FALSE outcome of the validation workflow - the critical decision point"
        required: "No"
        validation: "Set only after workflow completion"
        usage_notes: "TRUE = approved, FALSE = rejected, NULL = in progress"
      - name: "ValidationStage"
        type: "Enumeration"
        enumeration: "WorkflowStage"
        description: "Current stage in the validation process - tracks workflow progress"
        required: "Yes"
        validation: "Must be valid WorkflowStage enum value"
        usage_notes: "Updated as workflow progresses through each stage"
      - name: "CreatedDate"
        type: "DateTime"
        description: "When the validation process was initiated - for audit and tracking"
        required: "Yes"
        validation: "Auto-populated on creation"
        usage_notes: "Set when workflow is first created, never changed"
      - name: "CompletedDate"
        type: "DateTime"
        description: "When the validation process was completed - for performance metrics"
        required: "No"
        validation: "Set only when workflow reaches end state"
        usage_notes: "Used to calculate processing time and SLA compliance"
      - name: "InitiatedBy"
        type: "String"
        length: 50
        description: "User who initiated the validation workflow - for accountability"
        required: "Yes"
        validation: "Must be valid user identifier"
        usage_notes: "Links to Administration.Account, used for audit trail"

  - name: "ImageAcquisition"
    description: "Entity for capturing and storing validation images - first step in LAB workflow"
    purpose: "Manages image capture process and initial quality assessment"
    usage: "Created during image acquisition task, referenced throughout workflow"
    security_notes: "Technicians can CRUD their own images, Admin can access all, Viewer read-only"
    attributes:
      - name: "ImageFile"
        type: "System.Image"
        description: "The actual image file captured for validation - core validation artifact"
        required: "Yes"
        validation: "Must be valid image format (JPG, PNG)"
        usage_notes: "Processed by quality validation algorithms"
      - name: "IsQualityApproved"
        type: "Boolean"
        description: "Whether the image quality meets validation standards - critical decision point"
        required: "Yes"
        validation: "Set by quality validation process"
        usage_notes: "TRUE continues workflow, FALSE terminates with rejection"
      - name: "TechnicianID"
        type: "String"
        length: 50
        description: "ID of the technician who captured the image - for accountability and XPath filtering"
        required: "Yes"
        validation: "Must match authenticated user for creation"
        usage_notes: "Used in XPath: [TechnicianID = $currentUser/Name]"
      - name: "AcquisitionDate"
        type: "DateTime"
        description: "When the image was captured - timestamp for sequencing and audit"
        required: "Yes"
        validation: "Auto-populated on creation"
        usage_notes: "Used for chronological ordering of images"
      - name: "QualityScore"
        type: "Decimal"
        length: 8
        description: "Numerical quality score (0-100) from automated assessment"
        required: "No"
        validation: "Must be between 0 and 100"
        usage_notes: "Higher scores indicate better quality, used for decision logic"
      - name: "ImageMetadata"
        type: "String"
        length: 500
        description: "Technical metadata about the image capture (resolution, camera settings, etc.)"
        required: "No"
        validation: "JSON format preferred"
        usage_notes: "Stored for technical analysis and troubleshooting"

  - name: "DetailedImageAcquisition"
    description: "Enhanced image processing and analysis - second stage after quality approval"
    purpose: "Handles detailed image processing when initial quality check passes"
    usage: "Created only when IsQualityApproved = TRUE, contains enhanced processing results"
    security_notes: "Same technician who did initial capture, Admin override capability"
    attributes:
      - name: "EnhancedImageFile"
        type: "System.Image"
        description: "Processed and enhanced version of the original image - higher quality analysis"
        required: "Yes"
        validation: "Must be derived from original ImageAcquisition image"
        usage_notes: "Used for detailed analysis and final validation"
      - name: "ProcessingStatus"
        type: "Enumeration"
        enumeration: "ProcessingStatus"
        description: "Current status of image processing - tracks enhancement progress"
        required: "Yes"
        validation: "Must be valid ProcessingStatus enum"
        usage_notes: "InProgress while processing, Completed when ready for analysis"
      - name: "ProcessedBy"
        type: "String"
        length: 50
        description: "User who processed the enhanced image - for XPath security and audit"
        required: "Yes"
        validation: "Must be authenticated user"
        usage_notes: "Used in XPath: [ProcessedBy = $currentUser/Name]"
      - name: "ProcessingDate"
        type: "DateTime"
        description: "When the image processing was completed - for workflow timing"
        required: "No"
        validation: "Set when processing status becomes Completed"
        usage_notes: "Used to calculate processing time and bottleneck analysis"
      - name: "ProcessingNotes"
        type: "String"
        length: 1000
        description: "Notes about the processing steps taken - technical documentation"
        required: "No"
        validation: "Free text, technical details"
        usage_notes: "Documents any manual adjustments or special processing"

  - name: "ImageAnalysis"
    description: "Automated analysis results of validation images - AI/algorithm processing stage"
    purpose: "Stores results from automated image analysis algorithms"
    usage: "Created by service tasks, consumed by KPI extraction and validation decision"
    security_notes: "System-generated, Technician read access, Admin full access"
    attributes:
      - name: "AnalysisResult"
        type: "String"
        length: 2000
        description: "Detailed analysis results in structured format - core algorithm output"
        required: "Yes"
        validation: "JSON format recommended for structured data"
        usage_notes: "Contains measurements, defect detection, compliance results"
      - name: "ConfidenceScore"
        type: "Decimal"
        length: 8
        description: "Confidence level of the analysis (0-1) - algorithm certainty measure"
        required: "Yes"
        validation: "Must be between 0 and 1"
        usage_notes: "Higher values indicate more reliable analysis results"
      - name: "AnalysisDate"
        type: "DateTime"
        description: "When the analysis was performed - for audit and performance tracking"
        required: "Yes"
        validation: "Auto-populated by analysis service"
        usage_notes: "Used to track analysis processing time"
      - name: "AnalysisAlgorithm"
        type: "String"
        length: 100
        description: "Name/version of the analysis algorithm used - for traceability"
        required: "Yes"
        validation: "Must reference valid algorithm version"
        usage_notes: "Important for result interpretation and algorithm updates"
      - name: "ProcessedBy"
        type: "String"
        length: 50
        description: "User who initiated the analysis - for XPath security and audit"
        required: "Yes"
        validation: "Must be authenticated user"
        usage_notes: "Used in XPath: [ProcessedBy = $currentUser/Name]"

  - name: "KPIExtraction"
    description: "Key Performance Indicators extracted from validation process - metrics and measurements"
    purpose: "Captures quantitative measurements and performance metrics"
    usage: "Generated from ImageAnalysis results, used for final validation decision"
    security_notes: "Created by system, accessible based on user role and XPath constraints"
    attributes:
      - name: "KPIData"
        type: "String"
        length: 5000
        description: "Extracted KPI data in structured format - quantitative measurements"
        required: "Yes"
        validation: "JSON format with standardized KPI names"
        usage_notes: "Contains measurements like dimensions, tolerances, quality metrics"
      - name: "ExtractionDate"
        type: "DateTime"
        description: "When KPIs were extracted - timestamp for data freshness"
        required: "Yes"
        validation: "Auto-populated during extraction process"
        usage_notes: "Ensures KPIs reflect current analysis state"
      - name: "ExtractedBy"
        type: "String"
        length: 50
        description: "User who performed KPI extraction - for XPath security and audit"
        required: "Yes"
        validation: "Must be authenticated user"
        usage_notes: "Used in XPath: [ExtractedBy = $currentUser/Name]"
      - name: "KPIScore"
        type: "Decimal"
        length: 8
        description: "Overall KPI score for this validation - composite quality metric"
        required: "Yes"
        validation: "Calculated from individual KPI values"
        usage_notes: "Used in validation decision logic and reporting"
      - name: "Metrics"
        type: "String"
        length: 2000
        description: "Additional metrics in structured format - supplementary measurements"
        required: "No"
        validation: "JSON format for consistency"
        usage_notes: "Contains secondary measurements and derived values"

  - name: "ValidationResult"
    description: "Final validation decision and supporting information - human validation stage"
    purpose: "Records the final human validation decision and reasoning"
    usage: "Created by LAB validation task, contains final approve/reject decision"
    security_notes: "Only LABAdmin can create/modify, others have read access based on public flag"
    attributes:
      - name: "Result"
        type: "Enumeration"
        enumeration: "ValidationOutcome"
        description: "Final validation outcome - the critical business decision"
        required: "Yes"
        validation: "Must be valid ValidationOutcome enum value"
        usage_notes: "Approved/Rejected determines workflow TRUE/FALSE outcome"
      - name: "ValidatedBy"
        type: "String"
        length: 50
        description: "User who made the final validation decision - accountability for business decision"
        required: "Yes"
        validation: "Must be user with LABAdmin role"
        usage_notes: "Links to Administration.Account for full audit trail"
      - name: "ValidationDate"
        type: "DateTime"
        description: "When the validation decision was made - timestamp for business decision"
        required: "Yes"
        validation: "Auto-populated when decision is recorded"
        usage_notes: "Used for audit trail and decision timing analysis"
      - name: "Comments"
        type: "String"
        length: 1000
        description: "Comments explaining the validation decision - business rationale"
        required: "Yes"
        validation: "Must provide reasoning for decision"
        usage_notes: "Critical for audit trail and decision transparency"
      - name: "RecommendedActions"
        type: "String"
        length: 2000
        description: "Recommended next steps based on validation result - actionable guidance"
        required: "No"
        validation: "Helpful guidance for follow-up actions"
        usage_notes: "Provides direction for approved or rejected products"

  - name: "ValidationReport"
    description: "Comprehensive report of the validation process - final documentation"
    purpose: "Generates formal documentation of the entire validation process"
    usage: "Created at workflow completion, used for compliance and archival"
    security_notes: "Public reports accessible to Viewer role, private reports restricted"
    attributes:
      - name: "ReportContent"
        type: "String"
        length: 10000
        description: "Full report content in structured format - complete validation documentation"
        required: "Yes"
        validation: "Must include all validation stages and results"
        usage_notes: "Contains executive summary, technical details, and conclusions"
      - name: "ReportGenerated"
        type: "DateTime"
        description: "When the report was generated - timestamp for report validity"
        required: "Yes"
        validation: "Auto-populated during report generation"
        usage_notes: "Indicates report freshness and generation sequence"
      - name: "GeneratedBy"
        type: "String"
        length: 50
        description: "User who generated the report - accountability for report creation"
        required: "Yes"
        validation: "Must be authenticated user"
        usage_notes: "Links to user account for audit purposes"
      - name: "ReportFormat"
        type: "Enumeration"
        enumeration: "ReportFormat"
        description: "Format of the report - output format specification"
        required: "Yes"
        validation: "Must be supported ReportFormat enum value"
        usage_notes: "PDF for formal reports, JSON for data exchange"
      - name: "ReportFile"
        type: "System.FileDocument"
        description: "Generated report file attachment - downloadable report document"
        required: "No"
        validation: "Must match specified ReportFormat"
        usage_notes: "Allows users to download formatted report"

  - name: "WorkflowAuditTrail"
    description: "Complete audit trail of all workflow activities - compliance and tracking"
    purpose: "Maintains detailed log of all actions taken during validation process"
    usage: "Created automatically by system for every significant action"
    security_notes: "Read access based on user role, full history for admin, own actions for technicians"
    attributes:
      - name: "Action"
        type: "String"
        length: 100
        description: "Description of the action performed - what happened"
        required: "Yes"
        validation: "Use standardized action descriptions"
        usage_notes: "Should clearly describe the action taken"
      - name: "ActionDate"
        type: "DateTime"
        description: "When the action was performed - precise timestamp for audit"
        required: "Yes"
        validation: "Auto-populated when action occurs"
        usage_notes: "Used for chronological audit trail reconstruction"
      - name: "PerformedBy"
        type: "String"
        length: 50
        description: "User who performed the action - accountability tracking"
        required: "Yes"
        validation: "Must be authenticated user"
        usage_notes: "Used in XPath: [PerformedBy = $currentUser/Name] for filtering"
      - name: "EntityChanged"
        type: "String"
        length: 50
        description: "Which entity was affected by this action - impact tracking"
        required: "Yes"
        validation: "Must reference valid entity name"
        usage_notes: "Helps track changes across the domain model"
      - name: "OldValue"
        type: "String"
        length: 500
        description: "Previous value before the change - change tracking"
        required: "No"
        validation: "Required for update actions"
        usage_notes: "Enables change history and rollback capabilities"
      - name: "NewValue"
        type: "String"
        length: 500
        description: "New value after the change - change tracking"
        required: "No"
        validation: "Required for create/update actions"
        usage_notes: "Shows the result of the action"
      - name: "IPAddress"
        type: "String"
        length: 45
        description: "IP address of the user who performed the action - security tracking"
        required: "No"
        validation: "Valid IPv4 or IPv6 format"
        usage_notes: "Supports both IPv4 (15 chars) and IPv6 (45 chars) addresses"

# Enumeration Definitions
enumerations:
  - name: "WorkflowStage"
    values:
      - "ImageAcquisition"
      - "QualityValidation"
      - "DetailedAcquisition"
      - "Analysis"
      - "KPIExtraction"
      - "LABValidation"
      - "ReportGeneration"
      - "Completed"

  - name: "ProcessingStatus"
    values:
      - "Pending"
      - "InProgress"
      - "Completed"
      - "Failed"
      - "RequiresReview"

  - name: "ValidationOutcome"
    values:
      - "Approved"
      - "Rejected"
      - "Pending"
      - "RequiresRework"
      - "ConditionalApproval"

  - name: "ReportFormat"
    values:
      - "PDF"
      - "HTML"
      - "JSON"
      - "XML"
      - "Excel"